import localFont from "next/font/local";
import "./globals.css";
import {Gothic_A1} from "@next/font/google"

const gothicA1 = Gothic_A1({
  subsets: ['latin'], // You can specify other subsets if needed
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // All available weights
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gothicA1.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
